# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/NETID/sambhavi/css343/turtle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/NETID/sambhavi/css343/turtle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/NETID/sambhavi/css343/turtle/CMakeFiles /home/NETID/sambhavi/css343/turtle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/NETID/sambhavi/css343/turtle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ass1_turtleprogram

# Build rule for target.
ass1_turtleprogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ass1_turtleprogram
.PHONY : ass1_turtleprogram

# fast build rule for target.
ass1_turtleprogram/fast:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/build
.PHONY : ass1_turtleprogram/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/main.cpp.s
.PHONY : main.cpp.s

turtleprogram.o: turtleprogram.cpp.o

.PHONY : turtleprogram.o

# target to build an object file
turtleprogram.cpp.o:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogram.cpp.o
.PHONY : turtleprogram.cpp.o

turtleprogram.i: turtleprogram.cpp.i

.PHONY : turtleprogram.i

# target to preprocess a source file
turtleprogram.cpp.i:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogram.cpp.i
.PHONY : turtleprogram.cpp.i

turtleprogram.s: turtleprogram.cpp.s

.PHONY : turtleprogram.s

# target to generate assembly for a file
turtleprogram.cpp.s:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogram.cpp.s
.PHONY : turtleprogram.cpp.s

turtleprogramtest.o: turtleprogramtest.cpp.o

.PHONY : turtleprogramtest.o

# target to build an object file
turtleprogramtest.cpp.o:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogramtest.cpp.o
.PHONY : turtleprogramtest.cpp.o

turtleprogramtest.i: turtleprogramtest.cpp.i

.PHONY : turtleprogramtest.i

# target to preprocess a source file
turtleprogramtest.cpp.i:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogramtest.cpp.i
.PHONY : turtleprogramtest.cpp.i

turtleprogramtest.s: turtleprogramtest.cpp.s

.PHONY : turtleprogramtest.s

# target to generate assembly for a file
turtleprogramtest.cpp.s:
	$(MAKE) -f CMakeFiles/ass1_turtleprogram.dir/build.make CMakeFiles/ass1_turtleprogram.dir/turtleprogramtest.cpp.s
.PHONY : turtleprogramtest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ass1_turtleprogram"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... turtleprogram.o"
	@echo "... turtleprogram.i"
	@echo "... turtleprogram.s"
	@echo "... turtleprogramtest.o"
	@echo "... turtleprogramtest.i"
	@echo "... turtleprogramtest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

